### ISSUE TITLE
VST & ASIO

### ISSUE THREAD

**Issue by rome2** [dliganov/Chaotic-DAW#3]
Great project and thank you very much for open sourcing it.

A small hint: You should remove the ASIO and VST SDKs from the source tree as redistribution of these two elements is strictly forbidden by Steinberg. I know it's a PITA that everyone who wants to compile the sources will have to acquire these SDK by himself but it's still better than having to deal with Steinberg's lawyers.

**Comment by dliganov** [comment]
Hello, thank you for this hint, I just forgot about that restriction with Steinberg stuff. Will remove them now.
